// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfrrXCDkl-RwFWCZRGTIZeHNBF-v_LpY',
    appId: '1:200450128918:web:70f3632b23b48b85ba0937',
    messagingSenderId: '200450128918',
    projectId: 'zomatominiapp',
    authDomain: 'zomatominiapp.firebaseapp.com',
    storageBucket: 'zomatominiapp.firebasestorage.app',
    measurementId: 'G-4DYY96MF4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHfhoXhs9Rj2y7PIjHv93awogSUUPv4Q',
    appId: '1:200450128918:android:3c6dcd1e77b157ddba0937',
    messagingSenderId: '200450128918',
    projectId: 'zomatominiapp',
    storageBucket: 'zomatominiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSSJxLaDha9Zq1nU136oxLYIoz-xPgDcQ',
    appId: '1:200450128918:ios:8b91abc382652454ba0937',
    messagingSenderId: '200450128918',
    projectId: 'zomatominiapp',
    storageBucket: 'zomatominiapp.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSSJxLaDha9Zq1nU136oxLYIoz-xPgDcQ',
    appId: '1:200450128918:ios:8b91abc382652454ba0937',
    messagingSenderId: '200450128918',
    projectId: 'zomatominiapp',
    storageBucket: 'zomatominiapp.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfrrXCDkl-RwFWCZRGTIZeHNBF-v_LpY',
    appId: '1:200450128918:web:059f8f9890c6bab6ba0937',
    messagingSenderId: '200450128918',
    projectId: 'zomatominiapp',
    authDomain: 'zomatominiapp.firebaseapp.com',
    storageBucket: 'zomatominiapp.firebasestorage.app',
    measurementId: 'G-0Q7M7X2K63',
  );
}
